name: "Deploy AKS with terraform"

on:
  push:
    branches: ["master"] #Applied when pushed on main branch
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      action:
        description: "select action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      confirm_destroy:
        description: 'Type "yes" to Confirm destroy action'
        required: false
        default: "no"

permissions:
  contents: read
  id-token: write

env:
  # Getting Azure creds from github secrets
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

jobs:
  terraform-deploy:
    name: "Terraform CI/CD (Dev)"
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./env/dev

    steps:
      # Checkout repo
      - name: checkout code
        uses: actions/checkout@v4

      # Install terraform in agent
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{secrets.ARM_CLIENT_ID}}
          tenant-id: ${{secrets.ARM_TENANT_ID}}
          subscription-id: ${{secrets.ARM_SUBSCRIPTION_ID}}

      # Terraform Init
      - name: Terraform init
        run: terraform init

      # Adjust formating
      - name: Terraform Format
        if: inputs.action != 'destroy'
        run: terraform fmt -check

      # Terrafrom Plan
      - name: Terraform Plan
        if: inputs.action != 'destroy'
        id: plan
        run: terraform plan
        continue-on-error: false

      # Step 6: Apply when push to master
      - name: Terraform Apply (Deploy to Azure)
        if: |
          (github.ref == 'refs/heads/master' && 
          github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && inputs.action == 'apply')
        run: terraform apply -auto-approve

      # Step 7: Destroy when 'destroy' is selected
      - name: Terraform Destroy (Delete Resources)
        if: |
          github.event_name == 'workflow_dispatch' &&
          inputs.action == 'destroy' &&
          inputs.confirm_destroy == 'yes'
        run: terraform destroy -auto-approve
